void digitacao();
int guessgame();
int intro();
void menu(int *faseatual, int *vidas);
void save_arquivo(int *vidas, int *faseatual);
void load_arquivo(int *vidas, int *faseatual);
void limpartela();
void inserir_vidas(int *vidas);
void desafio1();
void desafio2();
void pressenter();