void digitacao();
int guessgame();
int intro();
void menu(int *faseatual, int *vidas);
void save_arquivo(int *vidas, int *faseatual);
void load_arquivo(int *vidas, int *faseatual);
void limpartela();
void inserir_vidas(int *vidas);
void desafio1(int *vidas);
void desafio2(int *vidas);
void pressenter();
void remove_vida(int *vidas);
int userinput(int maxopcoes);
void desafio3(int *vidas);
void desafio4(int *vidas);